import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'

export async function getStaticProps({ params }) {
  return {
    props: {
      geo: params.geo
    },
    revalidate: 60,
  }
}

export async function getStaticPaths() {
  return {
    paths: [],
    fallback: 'blocking'
  }
}

export default function Fixtures({ geo }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Timezone caching</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Arsenal vs Chelsea</h1>

        <p>15:00 BST - your local time in { geo }</p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
